### PR TITLE
Added support for context creation flags and texture/shader native handles

### PR DESCRIPTION
**Pull request by zsbzsb**
https://github.com/LaurentGomila/SFML/pull/779

### CODE REVIEW

**Comment by LaurentGomila** [comment]
Why sfUint32 for native handles? The C++ API defines them as unsigned int.

**Comment by zsbzsb** [comment]
Why do we even bother with sf::Uint32? The C++ API mixes them both interchangeably. Not to mention....

https://github.com/LaurentGomila/CSFML/blob/master/include/SFML/Config.h#L140
>typedef unsigned int sfUint32;

**Comment by LaurentGomila** [comment]
> Why do we even bother with sf::Uint32 / sfUInt32?

Fixed size types are needed in many situations. The fact that all our target platforms map sf::Uint32 it to unsigned int is just an implementation detail, which may not be true anymore in the future.

What's wrong with simply using the same types?

**Comment by zsbzsb** [comment]
>What's wrong with simply using the same types in CSFML?

Nothing at all. Commit updated.

**Pull request merged**
